version: '3.7'

services:
    gitlab:
      image: sameersbn/gitlab:16.8.1
      container_name: ${SERVICE_NAME}_${CONTAINER_NAME_GITLAB}
      restart: always
      depends_on:
        - postgresql
        - redis
      ports:
        - "${GITLAB_SSH_PORT}:22"
        - 1095:80
        - 1096:443
      expose:
        - 1095
        - 1096
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitlab-server.entrypoints=https"
        - "traefik.http.routers.gitlab-server.rule=Host(`${GITLAB_HOST}`)"
        - "traefik.http.routers.gitlab-server.tls=true"
        - "traefik.http.routers.gitlab-server.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.gitlab-server.service=gitlab-server-service"
        - "traefik.http.services.gitlab-server-service.loadbalancer.server.port=80"
        - "traefik.docker.network=webproxy"
      volumes:
        - ${SERVICE_DATA}/${SERVICE_NAME}/gitlab:/home/git/data:Z
#        - /home/development/gitlab-app/ssl-certs:/certs
        - /srv/services/cfg/gitlab/certs:/certs
      environment:
        - DEBUG=true

        - DB_ADAPTER=postgresql
        - DB_HOST=${SERVICE_NAME}_${CONTAINER_NAME_PGSQL}
        - DB_PORT=5432
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}

        - REDIS_HOST=${SERVICE_NAME}_${CONTAINER_NAME_REDIS}
        - REDIS_PORT=6379

        - TZ=UTC
        - GITLAB_TIMEZONE=${GITLAB_TIMEZONE}

        - GITLAB_HTTPS=true
        - SSL_SELF_SIGNED=false

        - GITLAB_HOST=${GITLAB_HOST}
        - GITLAB_PORT=80
        - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
        - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE}
        - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE}
        - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE}

        - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
        - GITLAB_ROOT_EMAIL=${GITLAB_ROOT_EMAIL}

        - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
        - GITLAB_NOTIFY_PUSHER=false

        - GITLAB_EMAIL=${GITLAB_EMAIL}
        - GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO}
        - GITLAB_INCOMING_EMAIL_ADDRESS=${GITLAB_INCOMING_EMAIL_ADDRESS}

        - GITLAB_PAGES_ENABLED=false

        - SMTP_ENABLED=${SMTP_ENABLED}
        # - SMTP_DOMAIN=${SMTP_DOMAIN}
        # - SMTP_HOST=${SMTP_HOST}
        # - SMTP_PORT=${SMTP_PORT}
        # - SMTP_USER=${SMTP_USER}
        # - SMTP_PASS=${SMTP_PASS}
        # - SMTP_STARTTLS=${SMTP_STARTTLS}
        # - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}

        - IMAP_ENABLED=false

        - LDAP_ENABLED=${LDAP_ENABLED}
        - LDAP_LABEL=${LDAP_LABEL}
        - LDAP_HOST=${LDAP_HOST}
        - LDAP_PORT=${LDAP_PORT}
        - LDAP_UID=${LDAP_UID}
        - LDAP_METHOD=${LDAP_METHOD}
        - LDAP_VERIFY_SSL=${LDAP_VERIFY_SSL}
        - LDAP_ACTIVE_DIRECTORY=${LDAP_ACTIVE_DIRECTORY}
        - LDAP_BASE=${LDAP_BASE}
        - LDAP_USER_FILTER=${LDAP_USER_FILTER}
        - LDAP_BIND_DN=${LDAP_BIND_DN}
        - LDAP_PASS=${LDAP_PASS}

        - GITLAB_REGISTRY_ENABLED=false
        # - GITLAB_REGISTRY_HOST=${REGISTRY_HOST}
        # - GITLAB_REGISTRY_API_URL=http://registry:5000/
        # - GITLAB_REGISTRY_KEY_PATH=/certs/registry.key
      healthcheck:
        test: ["CMD", "/usr/local/sbin/healthcheck"]
        interval: 1m
        timeout: 5s
        retries: 5
        start_period: 2m
      networks:
        - ${WEBPROXY_NETWORK}
        - ${SERVICE_NETWORK}
    # registry:
    #   image: registry:latest
    #   container_name: ${SERVICE_NAME}_${CONTAINER_NAME_REGISTRY}
    #   restart: always
    #   expose:
    #     - 5000
    #   labels:
    #     - "traefik.enable=true"
    #     - "traefik.http.routers.gitlab-registry.entrypoints=https"
    #     - "traefik.http.routers.gitlab-registry.rule=Host(`${REGISTRY_HOST}`)"
    #     - "traefik.http.routers.gitlab-registry.tls=true"
    #     - "traefik.http.routers.gitlab-registry.tls.certresolver=letsEncrypt"
    #     - "traefik.http.services.gitlab-registry-service.loadbalancer.server.port=5000"
    #     - "traefik.docker.network=webproxy"
    #   volumes:
    #     - ${SERVICE_DATA}/${SERVICE_NAME}/gitlab/shared/registry:/registry
    #     - ./ssl-certs:/certs
    #   environment:
    #     - REGISTRY_AUTH_TOKEN_AUTOREDIRECT=false
    #     - REGISTRY_LOG_LEVEL=debug
    #     - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    #     - REGISTRY_AUTH_TOKEN_REALM=https://${GITLAB_HOST}/jwt/auth
    #     - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
    #     - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
    #     - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
    #     - REGISTRY_STORAGE_DELETE_ENABLED=true
    #     # - REGISTRY_STORAGE=s3
    #     # - REGISTRY_STORAGE_S3_ACCESSKEY=${REGISTRY_STORAGE_S3_ACCESSKEY}
    #     # - REGISTRY_STORAGE_S3_SECRETKEY=${REGISTRY_STORAGE_S3_SECRETKEY}
    #     # - REGISTRY_STORAGE_S3_REGIONENDPOINT=${REGISTRY_STORAGE_S3_REGIONENDPOINT}
    #     # - REGISTRY_STORAGE_S3_REGION=${REGISTRY_STORAGE_S3_REGION}
    #     # - REGISTRY_STORAGE_S3_BUCKET=${REGISTRY_STORAGE_S3_BUCKET}
    #     # - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=inmemory
    #   networks:
    #     - ${WEBPROXY_NETWORK}
    #     - ${SERVICE_NETWORK}
    postgresql:
      image: sameersbn/postgresql:14-20230628
      container_name: ${SERVICE_NAME}_${CONTAINER_NAME_PGSQL}
      restart: always
      environment:
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
        - DB_EXTENSION=pg_trgm,btree_gist
      volumes:
        - ${SERVICE_DATA}/${SERVICE_NAME}/postgresql:/var/lib/postgresql:Z
      networks:
        - ${SERVICE_NETWORK}
    redis:
      restart: always
      image: redis:6.2.6
      container_name: ${SERVICE_NAME}_${CONTAINER_NAME_REDIS}
      command:
        - --loglevel warning
      volumes:
        - ${SERVICE_DATA}/${SERVICE_NAME}/redis:/var/lib/redis:Z
      networks:
        - ${SERVICE_NETWORK}
networks:
    service:
        name: ${SERVICE_NETWORK}
    webproxy:
        name: ${WEBPROXY_NETWORK}
        external: true
